[mypy]
python_version = 3.11

ignore_missing_imports = True

explicit_package_bases = True

exclude = venv

disable_error_code = name-defined


[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-joblib.*]
ignore_missing_imports = True

[mypy-bcrypt.*]
ignore_missing_imports = True

[mypy-flask_migrate.*]
ignore_missing_imports = True