"""create comercio table

Revision ID: 197e3d2bff5e
Revises: 2174ee38003b
Create Date: 2026-05-31 19:36:47.652883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197e3d2bff5e'
down_revision = '2174ee38003b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entidad_id', sa.BigInteger(), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('horario_apertura', sa.String(length=20), nullable=True),
    sa.Column('horario_cierre', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entidad_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comercios')
    # ### end Alembic commands ###
