"""initial schema

Revision ID: 2174ee38003b
Revises: 
Create Date: 2026-05-31 18:10:00.760715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2174ee38003b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personas_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_personas_email'), ['email'], unique=True)

    op.create_table('auditoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('persona_id', sa.BigInteger(), nullable=True),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_evento'), ['evento'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_severidad'), ['severidad'], unique=False)

    op.create_table('entidades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_entidad', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('owner_persona_id', sa.BigInteger(), nullable=False),
    sa.Column('email_contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_rechazo', sa.DateTime(), nullable=True),
    sa.Column('rechazado_por', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['rechazado_por'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entidades_nombre'), ['nombre'], unique=True)

    op.create_table('usuarios_auth',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('persona_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('estado_sesion', sa.String(length=20), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    with op.batch_alter_table('usuarios_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_auth_username'), ['username'], unique=True)

    op.create_table('consorcios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entidad_id', sa.BigInteger(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('cantidad_unidades', sa.Integer(), nullable=False),
    sa.Column('cantidad_pisos', sa.Integer(), nullable=True),
    sa.Column('tiene_seguridad', sa.Boolean(), nullable=True),
    sa.Column('tiene_cochera', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entidad_id')
    )
    op.create_table('persona_entidad',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('persona_id', sa.BigInteger(), nullable=False),
    sa.Column('entidad_id', sa.BigInteger(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona_entidad')
    op.drop_table('consorcios')
    with op.batch_alter_table('usuarios_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_auth_username'))

    op.drop_table('usuarios_auth')
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidades_nombre'))

    op.drop_table('entidades')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_severidad'))
        batch_op.drop_index(batch_op.f('ix_auditoria_evento'))

    op.drop_table('auditoria')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personas_email'))
        batch_op.drop_index(batch_op.f('ix_personas_documento'))

    op.drop_table('personas')
    # ### end Alembic commands ###
