"""create rol_permisos table

Revision ID: f58ffbc4f1aa
Revises: ef9eb3fde31d
Create Date: 2026-06-10 02:51:34.934558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58ffbc4f1aa'
down_revision = 'ef9eb3fde31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('rol_permisos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('permiso_id', sa.BigInteger(), nullable=False),
    sa.Column('asignado_por', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_por'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permiso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
